linters-settings:
  errcheck:
    check-type-assertions: true
  forbidigo:
    # Forbid the following identifiers (list of regexp).
    # Default: ["^(fmt\\.Print(|f|ln)|print|println)$"]
    forbid:
      - '^(fmt\.(Print|Error)(|f|ln)|print|println)$'
    # Exclude godoc examples from forbidigo checks.
    # Default: true
    # exclude_godoc_examples: false
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: "gitlab.szzhijing.com"
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(gitlab.szzhijing.com) # Custom section: groups all imports with the specified Prefix.
      # - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      # - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
  depguard:
    # Rules to apply.
    #
    # Variables:
    # - File Variables
    #   you can still use and exclamation mark ! in front of a variable to say not to use it.
    #   Example !$test will match any file that is not a go test file.
    #
    #   `$all` - matches all go files
    #   `$test` - matches all go test files
    #
    # - Package Variables
    #
    #  `$gostd` - matches all of go's standard library (Pulled from `GOROOT`)
    #
    # Default: Only allow $gostd in all files.
    rules:
      # Name of a rule.
      main:
        # Used to determine the package matching priority.
        # There are three different modes: `original`, `strict`, and `lax`.
        # Default: "original"
        list-mode: lax
        # List of file globs that will match this list of settings to compare against.
        # Default: $all
        files:
          - "$all"
        # List of allowed packages.
        # allow:
        #   - $gostd
        #   - github.com/go-kratos
        # Packages that are not allowed where the value is a suggestion.
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: not allowed
          - pkg: "reflect"
            desc: not allowed
          - pkg: "errors"
            desc: Should be replaced by github.com/pkg/errors

  # govet:
    # check-shadowing: true ## TODO: 启用

  lll:
    line-length: 200
  misspell:
    locale: US
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    # - funlen ## TODO: 启用
    # - gochecknoinits
    - goconst
    # - gocritic  ## TODO: 启用
    # - gocyclo ## TODO: 启用
    - gofmt
    - goimports
    # - gomnd ## TODO: 启用
    - goprintffuncname
    # - gosec ## TODO: 启用
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    # more
    - revive
    - gci
    - errorlint
    - forbidigo
    - forcetypeassert
    # - errchkjson ## TODO: 启用
    # - goerr113 ## TODO: 启用
    - tagliatelle
    # - wrapcheck ## TODO: 启用

run:
  timeout: 5m
  go: "1.22"
